added hw-10
Olha-Zhernosek/projector_homeworks pull request #2
Opened 2023-08-24 23:07 UTC by Olha-Zhernosek

перевиклала те саме

2023-08-25 17:45 UTC, bielanm requested changes
Привіт!

А ще ж має бути частина з numpy? Десь загубилась?)

2023-08-25 17:45 UTC, bielanm commented on hw_10/requirements.txt
> +numpy==1.24.4
Зазвичай є практика додавати тільки ті пакет в requirements.txt, від яких залежить проєкт. В твоєму випадку це лише numpy, а ти додала все що в тебе є встановлене.
Спробуй команду: `pip freeze | grep numpy > requirements.txt`

2023-08-26 19:35 UTC, Olha-Zhernosek commented
привіт, зробила віртуальне середовище, в ньому встановила бібліотекe, вона і пішла у новий requirements.txt

2023-08-28 11:29 UTC, bielanm commented
Треба додати назву папки з віртуаленвом до `.gitignor`.

2023-08-28 11:32 UTC, bielanm commented
Ну і не забудь видалити з репозиторію папку `venv_hw_10/`

2023-08-28 14:47 UTC, Olha-Zhernosek commented
привіт) додала до гіт_ігнор своє віртуальне, а саму папку із віртуальним видалила з репозиторію

2023-08-28 21:50 UTC, bielanm commented
4. Write a script that imports numpy. Execute code from their site (https://numpy.org/) and run it on a local computer

ось оцієї частини немає наче

2023-08-29 18:12 UTC, Olha-Zhernosek commented
але ж доданий файл з назвою np.py містить той код із посилання, чи неправильно?

2023-08-29 18:13 UTC, Olha-Zhernosek commented
і у коментарях до дз на проджі додавала скрін про всяк випадок

2023-08-30 14:54 UTC, bielanm approved these changes

2023-08-30 16:48 UTC, merged